### ISSUE TITLE
no start after update

### ISSUE THREAD

**Issue by Tobi7889** [rdmtc/RedMatic#187] opened 2019-04-11 16:09 UTC
Today i updated RedMatic on my Rasperrymatic from 2.8 to 4.1.0, now it does not start with following error code:

Apr 11 18:07:11 hm-ccu daemon.info redmatic: RedMatic v4.1.0 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Apr 11 18:07:11 hm-ccu daemon.info redmatic: Starting Node-RED
Apr 11 18:07:11 hm-ccu daemon.err node-red: Node-RED exited with non-zero exit status 139

Anyone with an idea?

**Comment by hobbyquaker** [comment] 2019-04-11 16:24
Hmm... Can you please set the Loglevel in the RedMatic UI to Debug, try to start again and see if there is more information? Also worth a try: start in Safe-Mode, if this works the root cause is located in the Flows or Nodes. 
* https://github.com/rdmtc/RedMatic/wiki/Loglevel
* https://github.com/rdmtc/RedMatic/wiki/Safe-Mode

**Comment by Tobi7889** [comment] 2019-04-11 16:41
The problem was, it does not start in safe mode also.

Due to the urgency, I completely uninstalled and reinstalled the redmatic, it works now.
Sorry, that i does not have used loglevel for debugging.

**Comment by hobbyquaker** [comment] 2019-04-11 16:56
Ok. So it's alright to close this issue?

**Comment by hobbyquaker** [comment] 2019-04-11 16:56
Ok. So it's alright to close this issue?

**Comment by jp112sdl** [comment] 2019-04-12 12:22
>  Node-RED exited with non-zero exit status 139

I had the same issue after updating from 4.0.3 to 4.1.1

There were some _port already in use_ hints in /var/log/messages and I saw an already running `node-red` process. Removed it with `killall` the easy way 🤓 
After that, NodeRED started correctly.

**Closed** 2019-04-12 18:08 UTC
Labels: awaiting-feedback, to be clarified
